using System.Text.Json.Serialization;

namespace OpenShock.SDK.CSharp.Problems;

public class ProblemDetails
{
    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
    /// dereferenced, it provide human-readable documentation for the problem type
    /// (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be
    /// "about:blank".
    /// </summary>
    [JsonPropertyOrder(-5)]
    [JsonPropertyName("type")]
    public required string Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </summary>
    [JsonPropertyOrder(-4)]
    [JsonPropertyName("title")]
    public required string Title { get; set; }

    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyOrder(-3)]
    [JsonPropertyName("status")]
    public required int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyOrder(-2)]
    [JsonPropertyName("detail")]
    public string? Detail { get; set; }
    
    /// <summary>
    /// Request Id for tracing the problem in the logs
    /// </summary>
    [JsonPropertyName("requestId")]
    public required string RequestId { get; set; } 
}